add_rules("mode.debug", "mode.release")

target("windows7_Activation")
    add_rules("qt.widgetapp")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/*.ui")
    add_files("src/*.h")
    add_files("src/*.rc")
    add_frameworks("QtNetwork")